#!/usr/bin/env bash
# setup_network.sh — Idempotent host network setup for IoT emulation lab
# Creates br0 bridge, configures DHCP via dnsmasq, enables NAT.
# Must be run with sudo.
set -euo pipefail

BRIDGE="br0"
BRIDGE_IP="192.168.100.1"
BRIDGE_CIDR="${BRIDGE_IP}/24"
DHCP_RANGE_START="192.168.100.10"
DHCP_RANGE_END="192.168.100.50"
DHCP_LEASE="12h"
DNSMASQ_PID="/run/dnsmasq-br0.pid"
DNSMASQ_CONF="/etc/dnsmasq.d/iot-lab.conf"
DNSMASQ_LEASE_FILE="/var/lib/misc/dnsmasq-br0.leases"
LOG_DIR="$HOME/iot-lab/logs"

# ---------- helper ----------
info()  { echo "[+] $*"; }
warn()  { echo "[!] $*"; }
die()   { echo "[ERROR] $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "This script must be run as root (use sudo)."

# ---------- 1. Install missing packages ----------
PACKAGES=(qemu-system-mips qemu-system-arm binwalk bridge-utils dnsmasq iptables)
MISSING=()
for pkg in "${PACKAGES[@]}"; do
    if ! dpkg -s "$pkg" &>/dev/null; then
        MISSING+=("$pkg")
    fi
done
if [[ ${#MISSING[@]} -gt 0 ]]; then
    info "Installing missing packages: ${MISSING[*]}"
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${MISSING[@]}"
else
    info "All required packages already installed."
fi

# ---------- 2. Create bridge ----------
if ip link show "$BRIDGE" &>/dev/null; then
    info "Bridge $BRIDGE already exists."
else
    info "Creating bridge $BRIDGE ..."
    ip link add name "$BRIDGE" type bridge
fi

# Assign IP if not already set
if ip addr show "$BRIDGE" | grep -q "$BRIDGE_IP"; then
    info "Bridge $BRIDGE already has $BRIDGE_CIDR."
else
    # Flush any stale addresses first
    ip addr flush dev "$BRIDGE" 2>/dev/null || true
    info "Assigning $BRIDGE_CIDR to $BRIDGE ..."
    ip addr add "$BRIDGE_CIDR" dev "$BRIDGE"
fi

# Bring up
ip link set "$BRIDGE" up
info "Bridge $BRIDGE is UP."

# ---------- 3. Configure dnsmasq ----------
mkdir -p /etc/dnsmasq.d
cat > "$DNSMASQ_CONF" <<EOF
# Auto-generated by iot-lab setup_network.sh
interface=${BRIDGE}
bind-interfaces
dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},${DHCP_LEASE}
dhcp-option=option:router,${BRIDGE_IP}
dhcp-option=option:dns-server,8.8.8.8,8.8.4.4
dhcp-leasefile=${DNSMASQ_LEASE_FILE}
log-facility=${LOG_DIR}/dnsmasq.log
EOF
info "Wrote dnsmasq config to $DNSMASQ_CONF"

# Kill any existing iot-lab dnsmasq instance (avoid duplicates)
if [[ -f "$DNSMASQ_PID" ]]; then
    kill "$(cat "$DNSMASQ_PID")" 2>/dev/null || true
    rm -f "$DNSMASQ_PID"
fi

# Also kill any system-wide dnsmasq that may conflict on br0
pkill -f "dnsmasq.*interface=${BRIDGE}" 2>/dev/null || true
sleep 1

# Touch the lease file
mkdir -p "$(dirname "$DNSMASQ_LEASE_FILE")"
touch "$DNSMASQ_LEASE_FILE"
mkdir -p "$LOG_DIR"

# Start our dedicated instance
dnsmasq --conf-file="$DNSMASQ_CONF" --pid-file="$DNSMASQ_PID" --no-daemon &
DNSMASQ_BG_PID=$!
disown "$DNSMASQ_BG_PID" 2>/dev/null || true
sleep 1

if kill -0 "$DNSMASQ_BG_PID" 2>/dev/null; then
    info "dnsmasq running (PID $DNSMASQ_BG_PID) on $BRIDGE."
else
    # Try daemon mode as fallback
    warn "Foreground dnsmasq died, trying daemon mode..."
    dnsmasq --conf-file="$DNSMASQ_CONF" --pid-file="$DNSMASQ_PID"
    info "dnsmasq started in daemon mode."
fi

# ---------- 4. IP forwarding ----------
CURRENT_FWD=$(sysctl -n net.ipv4.ip_forward)
if [[ "$CURRENT_FWD" -eq 1 ]]; then
    info "IP forwarding already enabled."
else
    sysctl -w net.ipv4.ip_forward=1
    info "IP forwarding enabled."
fi

# ---------- 5. NAT / MASQUERADE ----------
# Detect the default outbound interface
DEFAULT_IF=$(ip route show default | awk '/default/ {print $5; exit}')
if [[ -z "$DEFAULT_IF" ]]; then
    warn "No default route found — skipping MASQUERADE (no internet for guests)."
else
    # Add rule only if not already present
    if iptables -t nat -C POSTROUTING -s 192.168.100.0/24 -o "$DEFAULT_IF" -j MASQUERADE 2>/dev/null; then
        info "MASQUERADE rule for $DEFAULT_IF already exists."
    else
        iptables -t nat -A POSTROUTING -s 192.168.100.0/24 -o "$DEFAULT_IF" -j MASQUERADE
        info "Added MASQUERADE rule: 192.168.100.0/24 -> $DEFAULT_IF"
    fi
    # Allow forwarding to/from the bridge
    iptables -C FORWARD -i "$BRIDGE" -o "$DEFAULT_IF" -j ACCEPT 2>/dev/null ||
        iptables -A FORWARD -i "$BRIDGE" -o "$DEFAULT_IF" -j ACCEPT
    iptables -C FORWARD -i "$DEFAULT_IF" -o "$BRIDGE" -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null ||
        iptables -A FORWARD -i "$DEFAULT_IF" -o "$BRIDGE" -m state --state RELATED,ESTABLISHED -j ACCEPT
    info "Forwarding rules configured."
fi

# ---------- 6. Summary ----------
echo ""
echo "========================================="
echo "  IoT Lab Network Ready"
echo "  Bridge:    $BRIDGE ($BRIDGE_CIDR)"
echo "  DHCP:      $DHCP_RANGE_START - $DHCP_RANGE_END"
echo "  NAT via:   ${DEFAULT_IF:-N/A}"
echo "========================================="
